const DEFAULT_REMOTE_PROVIDER = "deepseek";
const REMOTE_PROVIDERS = new Set(["deepseek", "openai", "zhipuai"]);

const OPENAI_BASE_URL = "https://api.openai.com/v1";
const OPENAI_DEFAULT_MODEL = "gpt-4o-mini";
const OPENAI_DEFAULT_TIMEOUT_MS = 30000;

const DEEPSEEK_BASE_URL = "https://api.deepseek.com/v1";
const DEEPSEEK_DEFAULT_MODEL = "deepseek-chat";
const DEEPSEEK_DEFAULT_TIMEOUT_MS = 30000;

const ZHIPUAI_BASE_URL = "https://open.bigmodel.cn/api/paas/v4";
const ZHIPUAI_DEFAULT_MODEL = "glm-3-turbo";
const ZHIPUAI_DEFAULT_TIMEOUT_MS = 30000;

const PROVIDER_DEFAULT_BASE_URL = {
  openai: OPENAI_BASE_URL,
  deepseek: DEEPSEEK_BASE_URL,
  zhipuai: ZHIPUAI_BASE_URL,
};

const PROVIDER_DEFAULT_MODEL = {
  openai: OPENAI_DEFAULT_MODEL,
  deepseek: DEEPSEEK_DEFAULT_MODEL,
  zhipuai: ZHIPUAI_DEFAULT_MODEL,
};

const PROVIDER_DEFAULT_TIMEOUT_MS = {
  openai: OPENAI_DEFAULT_TIMEOUT_MS,
  deepseek: DEEPSEEK_DEFAULT_TIMEOUT_MS,
  zhipuai: ZHIPUAI_DEFAULT_TIMEOUT_MS,
};

const PROVIDER_API_KEY_ENV = {
  openai: "OPENAI_API_KEY",
  deepseek: "DEEPSEEK_API_KEY",
  zhipuai: "ZHIPUAI_API_KEY",
};

const DEFAULT_MAX_RETRIES = 2;
const MAX_PROPOSAL_CANDIDATES = 12;
const DEFAULT_CRITIC_ENABLED = true;
const DEFAULT_CRITIC_MAX_ROUNDS = 1;
const DEFAULT_CRITIC_MIN_PROPOSALS = 2;
const DEFAULT_CRITIC_MIN_CONFIDENCE = 0.72;

const PROTOCOL_NAME = "MQ_STRATEGY_CHAT";
const PROTOCOL_VERSION = "2.0";
const STRUCTURED_SCHEMA_VERSION = "2026-02-27";
const DECISION_SOURCE_FORMAT_MESSAGES = "langchain_messages_structured";

module.exports = {
  DEFAULT_REMOTE_PROVIDER,
  REMOTE_PROVIDERS,
  PROVIDER_DEFAULT_BASE_URL,
  PROVIDER_DEFAULT_MODEL,
  PROVIDER_DEFAULT_TIMEOUT_MS,
  PROVIDER_API_KEY_ENV,
  DEFAULT_MAX_RETRIES,
  MAX_PROPOSAL_CANDIDATES,
  DEFAULT_CRITIC_ENABLED,
  DEFAULT_CRITIC_MAX_ROUNDS,
  DEFAULT_CRITIC_MIN_PROPOSALS,
  DEFAULT_CRITIC_MIN_CONFIDENCE,
  PROTOCOL_NAME,
  PROTOCOL_VERSION,
  STRUCTURED_SCHEMA_VERSION,
  DECISION_SOURCE_FORMAT_MESSAGES,
};

