export { MerchantApi } from './merchantApi/index';
export type {
  AllianceConfig,
  AuditLogItem,
  AuditLogPage,
  CampaignStatusResult,
  FireSaleResult,
  MerchantCatalogItem,
  MerchantCatalogResult,
  MerchantContractStatusResult,
  MerchantOnboardResult,
  MerchantPhoneCodeResult,
  MerchantPhoneLoginResult,
  StrategyChatMessage,
  StrategyChatPendingReview,
  StrategyChatReviewResult,
  StrategyChatSessionResult,
  StrategyChatTurnResult,
  StrategyTemplate,
  StrategyTemplateBranch,
  TriggerRainEventResult,
} from './merchantApi/types';
