export { MerchantApi } from './merchantApi/index';
export type {
  AllianceConfig,
  AuditLogItem,
  AuditLogPage,
  MerchantCatalogItem,
  MerchantCatalogResult,
  MerchantContractStatusResult,
  MerchantOnboardResult,
  MerchantPhoneCodeResult,
  MerchantPhoneLoginResult,
  PolicyDecisionResult,
  StrategyChatPublishResult,
  StrategyChatMessage,
  StrategyChatMessagePage,
  StrategyChatPendingReview,
  StrategyChatEvaluationResult,
  StrategyChatReviewProgress,
  StrategyChatReviewResult,
  StrategyChatSessionResult,
  StrategyChatTurnResult,
  StrategyTemplate,
  StrategyTemplateBranch,
} from './merchantApi/types';
